export { default as Header } from "./Header";
export { default as Navbar } from "./Navbar";
export { default as NavLinks } from "./NavLinks";
export { default as Hero } from "./Hero";
export { default as ErrorElement } from "./ErrorElement";
export { default as ProductsGrid } from "./ProductsGrid";
export { default as FeaturedProducts } from "./FeaturedProducts";
export { default as SectionTitle } from "./SectionTitle";
export { default as OurBrands } from "./OurBrands";
export { default as OurBrands2 } from "./OurBrands2";
export { default as Footer } from "./Footer";
// export { default as ParallaxScroll } from "./ParallaxScroll";
// export { default as Navbar2 } from "./Navbar2";
